return {
    { name = "Strike", damage = 6, cost = 1 },
    { name = "Defend", block = 5, cost = 1 },
    { name = "Bash", damage = 8, cost = 2 },
    { name = "Slash", damage = 10, cost = 2 },
    { name = "Fireball", damage = 12, cost = 3 },
    { name = "Ice Shard", damage = 9, cost = 2 },
    { name = "Heal", heal = 10, cost = 2 },
    { name = "Poison", damage = 4, cost = 1, effect = "poison" },
    { name = "Shield", block = 8, cost = 2 },
    { name = "Lightning", damage = 15, cost = 3 },
    { name = "Smash", damage = 7, cost = 1 },
    { name = "Cleave", damage = 9, cost = 2 },
    { name = "Rage", damage = 5, cost = 1, effect = "rage" },
    { name = "Vampire Bite", damage = 6, cost = 2, heal = 5 },
    { name = "Thunder Clap", damage = 11, cost = 3 },
    { name = "Frost Nova", damage = 8, cost = 2, effect = "freeze" },
    { name = "Meteor", damage = 20, cost = 4 },
    { name = "Earthquake", damage = 14, cost = 3 },
    { name = "Blizzard", damage = 10, cost = 3, effect = "freeze" },
    { name = "Holy Light", heal = 15, cost = 3 },
    { name = "Shadow Bolt", damage = 13, cost = 3 },
    { name = "Arcane Missiles", damage = 7, cost = 2 },
    { name = "Divine Shield", block = 10, cost = 3 },
    { name = "Flamestrike", damage = 18, cost = 4 },
    { name = "Ice Barrier", block = 12, cost = 3 },
    { name = "Life Drain", damage = 9, cost = 2, heal = 5 },
    { name = "Whirlwind", damage = 12, cost = 3 },
    { name = "Frostbolt", damage = 8, cost = 2, effect = "freeze" },
    { name = "Chain Lightning", damage = 14, cost = 3 },
    { name = "Death Coil", damage = 16, cost = 4 }
}